#!/bin/bash

# update icons
/bin/touch --no-create /usr/share/icons/hicolor &>/dev/null || true
/usr/bin/gtk-update-icon-cache /usr/share/icons/* &>/dev/null || true

# extract assets
mkdir -p /usr/share/f.e.i.s
tar \
    --extract \
    --gzip \
    --directory /usr/share/f.e.i.s \
    --strip-components=1 \
    --file /tmp/f.e.i.s/assets.tar.gz
rm -f /tmp/f.e.i.s/assets.tar.gz